# Generated by Django 4.0.6 on 2022-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100, verbose_name='Ингридиент')),
                ('calories', models.FloatField(verbose_name='Ккал на 100гр')),
                ('price', models.FloatField(verbose_name='Цена за 100 гр')),
                ('amount', models.FloatField(default=0, verbose_name='Кол-во, гр')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
