# Generated by Django 4.0.6 on 2022-07-23 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_recipes', '0005_recipes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_of_month',
            field=models.CharField(default='no', max_length=100, verbose_name='Отметка "рецепт" месяца'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
