# Generated by Django 4.0.6 on 2022-07-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_recipes', '0006_recipes_recipe_of_month_alter_recipes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
    ]
